### PR TITLE
Update pymc version requirements.txt

### PR DESCRIPTION
**Pull request by juanitorduz**
This are moving fast heh https://github.com/pymc-devs/pymc/releases/tag/v5.15.0

### CODE REVIEW

**Comment by maresb** [comment]
Hard pinning pymc to 5.15.0 is pretty harsh, no? I'm not following closely, but is there a particular reason?

**Comment by juanitorduz** [comment]
> Hard pinning pymc to 5.15.0 is pretty harsh, no? I'm not following closely, but is there a particular reason?

Yes: see https://github.com/pymc-devs/pymc-bart/pull/162#issuecomment-2100243075 (and initial scope of the PR)

**Comment by juanitorduz** [comment]
@maresb, do you have a suggestion on how to handle this in a way to see if a new release breaks something and, if so, restrict the version?

**Comment by maresb** [comment]
I'd recommend a `<` pin to the next untested version, e.g. `<5.15`. Otherwise you won't be compatible with patch releases. Also, more broadly this prevents people from using it with previous versions. Is it incompatible with 5.13? If so, then it should be something like `<=5.14,<5.15`.

More broadly, we should do more testing.

**Comment by juanitorduz** [comment]
ok! Let's see :) https://github.com/pymc-devs/pymc-bart/pull/164

**Pull request merged**
